name: Visual Studio

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Build (x64)
      run: |
        mkdir package\x64\plugins
        cmake -B build64 -A x64
        cmake --build build64 --config Release
        copy build64\Release\*.dp64 package\x64\plugins\

    - name: Build (x32)
      run: |
        mkdir package\x32\plugins
        cmake -B build32 -A Win32
        cmake --build build32 --config Release
        copy build32\Release\*.dp32 package\x32\plugins\
    
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ github.sha }}
        path: package/
    
    - name: Compress artifacts
      uses: papeloto/action-zip@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: package/
        dest: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}